// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/career.tsx";
import * as $4 from "./routes/en/career.tsx";
import * as $5 from "./routes/en/index.tsx";
import * as $6 from "./routes/greet/[name].tsx";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/ThemeSwitchButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/career.tsx": $3,
    "./routes/en/career.tsx": $4,
    "./routes/en/index.tsx": $5,
    "./routes/greet/[name].tsx": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/ThemeSwitchButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
